server:
  port: 8080
  
  
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cadastropessoas
    username: root
    password: 1308
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
